#!/bin/bash
#bash completion for vps-lxc

_vps-lxc () {

    # source/find the configuration
    if [ -z "${VPS_CONF}" ]; then
        local x l=vps-lxc s=${l%-lxc}
        # this will break immediately on the first/best hit
        for x in {,/usr,/vps,/usr/local,/opt,/opt/local}/etc/{${l}/${l},${s}/${s}}.conf; do
            [ -f "${x}" ] && VPS_CONF=${x} && break
        done
        [ -z "${VPS_CONF}" ] && return 1
    fi
    ! . ${VPS_CONF} 2>&- && return 1

    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local cmd run def dom tpl
    cmd="$(ls -1 ${VPS_USR}/lib/${VPS_NAME}/cmd | sed -e "/[^a-z]/d")"
    run="$(netstat -ax | grep -e "/command\$" | sed -e "s,.*LISTENING.*/\(.*\)/command\$,\\1,g")"
    def="$(ls ${VPS_LXC})"
    dom="$(ls ${VPS_VAR}/lib/${VPS_NAME}/dom)"
    tpl="$(ls ${VPS_VAR}/lib/${VPS_NAME}/tpl)"

    case "${prev}" in
    vps-lxc)
        # self
        COMPREPLY=( $(compgen -W "help ${cmd}" -- ${cur}) )
        return 0
    ;;
    define)
        # not in lxc but in dom
        COMPREPLY=( $(compgen -W "help $(comm -23 <(echo "${dom}" | tr " " "\n") <(echo "${def}" | tr " " "\n"))" -- ${cur}) )
        return 0
    ;;
    edit)
        # use dom
        COMPREPLY=( $(compgen -W "help ${dom}" -- ${cur}) )
        return 0
    ;;
    enter)
        # use run
        COMPREPLY=( $(compgen -W "help ${run}" -- ${cur}) )
        return 0
    ;;
    ls)
        COMPREPLY=( $(compgen -W "help dom tpl" -- ${cur}) )
        return 0
    ;;
    mkdom)
        # would like intelligent option completion here
        COMPREPLY=( $(compgen -W "help" -- ${cur}) )
        return 0
    ;;
    mktpl)
        # would like intelligent option completion here
        COMPREPLY=( $(compgen -W "help" -- ${cur}) )
        return 0
    ;;
    monitor)
        # use run
        COMPREPLY=( $(compgen -W "help ${run}" -- ${cur}) )
        return 0
    ;;
    reboot)
        # use run
        COMPREPLY=( $(compgen -W "help ${run}" -- ${cur}) )
        return 0
    ;;
    rmdom)
        # use dom
        COMPREPLY=( $(compgen -W "help ${dom}" -- ${cur}) )
        return 0
    ;;
    rmtpl)
        # use tpl
        COMPREPLY=( $(compgen -W "help ${tpl}" -- ${cur}) )
        return 0
    ;;
    start)
        # def against run unique
        COMPREPLY=( $(compgen -W "help $(comm -23 <(echo "${def}" | tr " " "\n") <(echo "${run}" | tr " " "\n"))" -- ${cur}) )
        return 0
    ;;
    stop)
        # run against def unique
        COMPREPLY=( $(compgen -W "help ${run}" -- ${cur}) )
        return 0
    ;;
    tree)
        # none
        COMPREPLY=( $(compgen -W "help" -- ${cur}) )
        return 0
    ;;
    proto)
        COMPREPLY=( $(compgen -W "help" -- ${cur}) )
        return 0
    ;;
    esac

}
complete -F _vps-lxc vps-lxc
